### ISSUE TITLE
Example action fails during setup

### ISSUE THREAD

**Issue by NiloCK** [charmbracelet/vhs-action#137]
Great tool (vhs), excellent integration here. Thanks.

This action run:
https://github.com/NiloCK/tuido/actions/runs/5095989680/jobs/9161452434?pr=8

was triggered by this yml config:
https://github.com/NiloCK/tuido/blob/vhs-wip/.github/workflows/vhs.yml

which is a very slight modification from the sample given in this repo:
https://github.com/charmbracelet/vhs-action/blob/main/examples/auto-commit.yml

From the [run report](https://github.com/NiloCK/tuido/actions/runs/5095989680/jobs/9161452434?pr=8#step:3:40), the action fails to install vhs during its run:

> Error: Unable to find VHS version 0.5.0 for platform Linux and architecture x86_64

Any tips?

**Comment by koki-develop** [comment]
I had the same problem.
It appears that this is due to a change in the format of the archive file name in the release asset since vhs 0.5.0.

- \>= [0.5.0](https://github.com/charmbracelet/vhs/releases/tag/v0.5.0) : `vhs_{platform}_{arch}.tar.gz`
- <= [0.4.0](https://github.com/charmbracelet/vhs/releases/tag/v0.4.0) : `vhs_{version}_{platform}_{arch}.tar.gz`

vhs-action attempts to retrieve the archive file assuming the format up to v0.4.0, so an error occurs.

https://github.com/charmbracelet/vhs-action/blob/92b589ec1b6cff26ffa0464d9644c258f4d1c0a2/src/installer.ts#L81

A temporary fix is to specify a version prior to 0.4.0 for `version`.
Like this:

```yaml
      - uses: charmbracelet/vhs-action@v1
        with:
          version: v0.4.0
          path: ./path/to/tape
```
